commission: 0.0
data:
  higher_tf_file: null
  main_file: data.csv
data_source: synthetic
initial_capital: 10000.0
monte_carlo:
  confidence_level: 0.95
  enabled: true
  num_simulations: 1000
mt5:
  login: null
  password: null
  server: null
num_bars: 1000
plot:
  enabled: true
  file: backtest_results.png
  save: false
  show: true
results_file: backtest_results.csv
save_results: false
slippage: 0.0
strategy:
  allow_longs: true
  allow_shorts: true
  atr_period: 14
  higher_timeframe: D1
  macd_fast_period: 12
  macd_signal_period: 9
  macd_slow_period: 26
  rsi_period: 7
  sl_multiplier: 1.5
  stoch_k_period: 14
  stoch_smooth_period: 3
  supertrend_multiplier: 4.0
  supertrend_period: 10
  symbol: EURUSD
  timeframe: H1
  tp_multiplier: 3.0
trades_file: backtest_trades.csv
trend_strength: 0.6
volatility: 1.0
